project:
  type: website

website:
  title: "{{< var jpe.short >}} Replicator Website"
  favicon: img/jpeicon.png
  page-footer: 
    left: "{{< var jpe.short >}} Data Editor: [{{< var de.mail >}}]({{< var de.mail >}}) <br> {{< var jpe.short >}} Journal Office: [{{< var jpe.mail >}}]({{< var jpe.mail >}})"
    center: "© [Florian Oswald](https://floswald.github.io) {{< var de.year >}}"
    right:
      - icon: github
        href: https://github.com/JPE-Reproducibility/jpereplicators

  sidebar:
    style: docked
    logo: img/jpe.jpg
    alignment: left
    contents: 
      - href: training/git-prereq.qmd
        text: Pre workshop
      - href: training/git-slides.qmd
        text: Git workshop        
      - href: replicator-resources.qmd
        text: Resources
      
